### ISSUE TITLE
README.md

### ISSUE THREAD

**Issue by Villanuevand** [ngVenezuela/wengy-ven#1]
Actualizar `readme.md`.

**Comment by Villanuevand** [comment]
@leocabeza Tengo un gist de base para el este issue, lo puedo colocar, y mientras vayamos avanzando lo vamos llenando ... 
¿Que opinas?

**Comment by leocabeza** [comment]
Si, me parece buena idea @Villanuevand

**Comment by Villanuevand** [comment]
Se agrego una plantilla base para el `readme.md`.
Queda pendiente realizar en ISSUE #12
