### ISSUE TITLE
Implementar Unit testing

### ISSUE THREAD

**Issue by leocabeza** [ngVenezuela/wengy-ven#11]
Implementar pruebas de Unit Testing

**Comment by Villanuevand** [comment]
¿Algún framework de preferencia? O tenemos rienda suelta?

**Comment by leocabeza** [comment]
Creería que cualquiera con buena documentación estaría bien

**Comment by davidjsalazarmoreno** [comment]
Jest 😀https://facebook.github.io/jest/

**Comment by Villanuevand** [comment]
@davidjsalazarmoreno ¿Tienes experiencia con Jest?

**Comment by davidjsalazarmoreno** [comment]
@Villanuevand Si, aunque cero experiencia con bots, podría montar un PR.

Quizás también exista algún testing framework especifico para los bots pero Jest me parece bastante multi-proposito y con buena curva de aprendizaje.

EDIT: Ya estoy en ello.

**Comment by davidjsalazarmoreno** [comment]
[PR por aquí](https://github.com/ngVenezuela/wengy-ven/pull/47)

**Comment by Villanuevand** [comment]
Aunque ya se implement unit test, creo que debemos cerrar este issue, y abrir una epica, para agregar las tareas de todas las cosas que se deben de testear.
Y así tener todo lo referente a test, organizado.

¿Que opinan? 

cc @leocabeza  @davidjsalazarmoreno  @jobsamuel

**Comment by davidjsalazarmoreno** [comment]
¡Fino!, me parece bien.

**Comment by Villanuevand** [comment]
Se cierra esta incidencia, y se crea una épica, para agrupar los componentes a testear.
