### ISSUE TITLE
Crear configuración de CircleCI

### ISSUE THREAD

**Issue by leocabeza** [ngVenezuela/wengy-ven#114]
**Estoy enviando un ...**  (marque con una "x")
```
[ ] Error reportado
[*] Solicitud de caracteristica, mejora

```

**Comportamiento Actual** 
No existe

**Comportamiento Esperado**
Generar una configuración en el root del repo para hacer CI con CircleCI (https://circleci.com) en el proyecto.

**Reproducción del Problema**
No existe

**Cual es el motivo / Caso util para cambiar el comportamiento?**
Despliegue automático cuando hay un nuevo commit en la rama `master`

**Por favor cuentamos sobre tu ambiente de desarrollo:**
No aplica

**Comment by JuanDelgadillo** [comment]
👏🏻

**Comment by leocabeza** [comment]
Cerrado en #118
