### ISSUE TITLE
Implementar docker

### ISSUE THREAD

**Issue by leocabeza** [ngVenezuela/wengy-ven#133]
**Estoy enviando un ...**  (marque con una "x")
```
[ ] Error reportado.
[*] Solicitud de caracteristica, mejora.

```

**Comportamiento Actual** 
No aplica

**Comportamiento Esperado**
Utilizar docker para desarrollo y producción para hacer más fácil el desarrollo a nuevos contribuidores

**Reproducción del Problema**
No aplica

**Cual es el motivo / Caso util para cambiar el comportamiento?**
Utilizar docker para desarrollo y producción para hacer más fácil el desarrollo a nuevos contribuidores

**Por favor cuentamos sobre tu ambiente de desarrollo:**
No aplica

**Comment by dianjuar** [comment]
Hola @leocabeza. He creado varios [docker-compose](https://github.com/bikecoders/docker-compose_wordpress) y me apasiona el asunto.

Pudiese ayudar con esto... Podrías indicar cuales son los programas que necesita tener instalado el repo para correr?
De momento se que node y npm...

**Comment by leocabeza** [comment]
Hola @dianjuar, los programas requeridos son:

- Node v7.10
- Redis server v3.2.9

`ngrok` si bien se menciona en la wiki, va a pasar como dependencia del proyecto, entonces no sería necesario.

Hay un script que se tiene en  ambiente de prueba y de producción que lo que haces es hacer fetch de los nuevos cambios y lanzar la aplicación a través de un comando, quizás esto también sea necesario hacerlo mediante docker (para que lo tengas en cuenta).

Cualquier duda me dices @dianjuar
