### ISSUE TITLE
Implementar Botan.io

### ISSUE THREAD

**Issue by leocabeza** [ngVenezuela/wengy-ven#134]
**Estoy enviando un ...**  (marque con una "x")
```
[ ] Error reportado
[*] Solicitud de caracteristica, mejora

```

**Comportamiento Actual** 
No existe

**Comportamiento Esperado**
Implementar analytics para el bot: http://botan.io/

**Reproducción del Problema**
No aplica

**Cual es el motivo / Caso util para cambiar el comportamiento?**
Permite a los administradores del grupo conocer la funcionalidad que le dan al bot

**Por favor cuentamos sobre tu ambiente de desarrollo:**
No aplica

**Comment by Villanuevand** [comment]
¡Genial Leo! GENIAL....

**Comment by moisesmorillo** [comment]
Toca mirar otra plataforma de analytics porque esta quedo deprecada https://github.com/botanio/sdk

**Comment by leocabeza** [comment]
Si @moisesmorillo, yo dejé esto abierto pero la razón por la cual no lo implementé es porqué estaba muy crudo, en la página destacan varias opciones, pero no he trabajado con ninguna:

https://chatbase.com/welcome
https://www.dashbot.io/
https://botanalytics.co/
