### ISSUE TITLE
Eliminar mensajes de bienvenida que contenga algún enlace http/s.

### ISSUE THREAD

**Issue by osnoser1** [ngVenezuela/wengy-ven#139]
**Estoy enviando un ...**  (marque con una "x")
```
[ ] Error reportado (Haz referencia al issue) => (Busca en github un issue o PR antés de enviar uno, NO olvides borrar esto).
[x] Solicitud de caracteristica, mejora.

```

**Comportamiento Actual**

Los mensajes de bienvenida al grupo con enlaces hay que borrarlos manualmente.

**Comportamiento Esperado**

El bot debería borrar este tipo de mensajes.

**Reproducción del Problema**

_No aplica_ 

**¿Cuál es el motivo / Caso util para cambiar el comportamiento?**

Automatización.

**Por favor cuéntanos sobre tu ambiente de desarrollo:**

_No aplica_

**Comment by JuanDelgadillo** [comment]
🎉

**Comment by leocabeza** [comment]
¿Puedo tomar este @osnoser1?

Creo que lo puedo expander un poco más y hacer una funcionalidad de detectar miembros que hagan spam.

* A veces un usuario puede tener un nombre de usuario "www midominiospam com".
* O a veces un usuario que luce legítimo reenvía contenido desde el canal que tiene el spam.
* Se podría investigar y ver si se hace algo personalizado o alguna otra librería que nos ayude.

Quizás lo más díficil sería determinar que se hace cuando un usuario hace spam o cuando un usuario sospechoso entra al grupo.

Lo único que se me ocurre:

* Enviar un mensaje al grupo de admins cuando se detecte un mensaje o usuario sospechoso (¿Y una acción para eliminarlo directamente desde allá?

**Comment by osnoser1** [comment]
Vale @leocabeza...
Por cierto, en estos días vi en un grupo que agregaron un bot que hacía que para que ingrese un nuevo miembro resolviera una captcha. Nunca lo había visto. Quizás esa también sea una solución viable.
¿Qué opinas?

**Comment by leocabeza** [comment]
Sería ideal, pero, ¿como sería lai integración? ¿existe ya una solución en una librería o servicio? ¿o es un bot aparte de wengy?

**Comment by leocabeza** [comment]
Yo creo que ya esto lo maneja join captcha bot
