### ISSUE TITLE
Migrar a Zeit

### ISSUE THREAD

**Issue by leocabeza** [ngVenezuela/wengy-ven#140]
**Comportamiento Actual** 
Se usa un hosting pago para correr el bot.

**Comportamiento Esperado**
Utilizar https://zeit.co/docs/other/faq

**Reproducción del Problema**
_No aplica_

**Cual es el motivo / Caso util para cambiar el comportamiento?**

**Por favor cuentamos sobre tu ambiente de desarrollo:**
No mantener un servidor privado

**Comment by Villanuevand** [comment]
Esto me parece muy bueno! 

Podrías darnos un poco más de contexto de como funciona Zeit y sus beneficios ?

**Comment by leocabeza** [comment]
> now allows you to take your JavaScript (Node.js) or Docker powered websites, applications and services to the cloud with ease, speed and reliability. In practical terms, any directory that contains a package.json or Dockerfile can be transported to the cloud with one command: now.

Lo que se quiere es que solo nos preocupemos por el desarrollo, y a la hora de hacer deploy o probar nuestro bot, corremos un comando.

Creo que su plan para OSS, nos puede ser más que suficiente:

https://zeit.co/pricing

**Comment by Villanuevand** [comment]
Great! Si quieres podemos hacer un Milestone sobre ello ... y poner tareas para que la gente pueda ayudar.
