### ISSUE TITLE
Agregar: "use strict; fallback"

### ISSUE THREAD

**Issue by Villanuevand** [ngVenezuela/wengy-ven#22]
Para correr typescript aún sino lo tienes actualizado.

**Comment by kkoci** [comment]
Hola, buenos días, ¿En cual rama lo puedo hacer? Hay varias, Saludos

**Comment by Villanuevand** [comment]
Aceptado  en `PR` #24 

Te invitamos a volver  a mirar  el `contributing.md` con nuevas actualizaciones y ejemplos en [este enlace](https://github.com/ngVenezuela/wengy-ven/blob/master/.github/CONTRIBUTING.md)

**Comment by kkoci** [comment]
Excelente, gracias! Seguro que si
