### ISSUE TITLE
Dar los buenos días

### ISSUE THREAD

**Issue by leocabeza** [ngVenezuela/wengy-ven#28]
**Estoy enviando un ...**  (marque con una "x")

```
[ ] Error reportado (Haz referencia al issue) => (Busca en github un issue o PR antés de enviar uno, NO olvides borrar esto).
[*] Solicitud de caracteristica, mejora.

```

**Comportamiento Actual** 
NO APLICA

**Comportamiento Esperado**
Dar los buenos días

**Reproducción del Problema**
NO APLICA

**Cual es el motivo / Caso util para cambiar el comportamiento?**
¿Qué mejor manera de comenzar el día que wengy-ven te dé los buenos días? Pienso que está es una característica sencilla de implementar

**Por favor cuentamos sobre tu ambiente de desarrollo:**
NO APLICA

**Comment by hostelix** [comment]
En que intervalo de hora dara los buenos dias? o los dara cada vez que algun miembro escriba "buenos dias comunidad" ?

**Comment by jobsamuel** [comment]
Sugiero dar los buenos días dentro de un rango de tiempo (ej: entre 7:00 - 8:00 AM) **sólo si** nadie ha dicho los _buenos días_ o escrito algo. Sería como romper el silencio. Considero que sería más humano y menos molesto a lo largo del tiempo.

**Comment by Villanuevand** [comment]
Alguien alguna vez comentó: Que deberíamos humanizar a wengy... 
@leocabeza , que tal si hacemos un **milestone** y categorizamos estos _issues_ ahí?  
Todo lo que tiene que ver con darle "inteligencia" a wengy...

Estoy atento a tu comentario  Leonardo...

**Comment by leocabeza** [comment]
Estoy de acuerdo con la estrategia que propone @jobsamuel, @hostelix. Imagino que hablamos de las GMT -4 (Hora de Venezuela)

**Comment by leocabeza** [comment]
@Villanuevand, habría que tomar en cuenta que ese _milestone_ "Humanizar a wengy" no tendría una fecha tope, y por lo tanto, en mi opinión, no cumpliría con la definición de milestone. Me parece que quedaría mejor como una **categoría**.

**Comment by Villanuevand** [comment]
@leocabeza si, realmente ninguno de los _milestones_ tiene fecha tope, por razones obvias. Tienes razón, pero podemos pensar un grupo de tareas para hacer interacción básica...

**Comment by jobsamuel** [comment]
Tal vez me equivoque, como suele suceder @Villanuevand, pero... ¿no sería mejor _wengy-ux_ un mejor nombre para esa categoría? Ya que se intenta mejorar la experiencia del usuario mas no la interacción; eso ya lo está haciendo con cada mejora. Claro, tal vez esté viendo las cosas desde otra perspectiva y esté totalmente errado.

**Comment by jobsamuel** [comment]
Sí @leocabeza, por lo menos yo voto porque se utilice **GMT -4**, ya que, por mas que un gran porcentaje esté fuera del país, la comunidad es venezolana :venezuela:

**Comment by Villanuevand** [comment]
@jobsamuel, Tienes razón eliminamos el _milestone_ y buscamos un _label_ adecuado.
