### ISSUE TITLE
Publicar feed de Twitter en el grupo

### ISSUE THREAD

**Issue by leocabeza** [ngVenezuela/wengy-ven#29]
**Estoy enviando un ...**  (marque con una "x")

```
[ ] Error reportado (Haz referencia al issue) => (Busca en github un issue o PR antés de enviar uno, NO olvides borrar esto).
[*] Solicitud de caracteristica, mejora. (Haz referencia al issue, marcado como "Mejora", NO olvides borrar esto)

```

**Comportamiento Actual** 
NO APLICA

**Comportamiento Esperado**
Si alguien hace un post en Twitter, mostrar el tuit en el grupo.

**Reproducción del Problema**
NO APLICA

**Cual es el motivo / Caso util para cambiar el comportamiento?**
Pienso que sería mejor hacer esto automático, que obligar al usuario a revisar el feed constantemente. Igual se puede hacer como un filtro para que sólo muestre tuits específicos con algunos hashtags.

**Por favor cuentamos sobre tu ambiente de desarrollo:**
NO APLICA

**Comment by dianjuar** [comment]
Yo utilizo un bot de telegram para esto, se llama [@tweets_bot](https://t.me/tweets_bot)
Claaaro es de uso personal.

No se si este bot se pueda incluir en el grupo o tenga alguna función para hacer esta misma funcionalidad en el grupo si se le invita.

**Comment by leocabeza** [comment]
Creo que sería mejor si se implementa la funcionalidad dentro del mismo bot, y no utilizar el tercero @dianjuar .

"No debería ser tan difícil"... https://www.npmjs.com/package/twitter y utilizar el stream API.

**Comment by dianjuar** [comment]
### Me asignaré este issue.
La verdad publican cosas interesantes en el twitter, motiva cuando uno comparte información y ustedes la twittean.

Me parece un buen improvement.

--------------

@Villanuevand puedes mover el card.

**Comment by leocabeza** [comment]
Cerrado en #77
