### ISSUE TITLE
Agregar encuesta para nuevos miembros

### ISSUE THREAD

**Issue by leocabeza** [ngVenezuela/wengy-ven#3]
A la hora de que un miembro entre al grupo de ngVenezuela, hacerle una mini-encuesta para saber como llego al grupo y guardar estos resultados para luego ser consultados.

**Comment by Villanuevand** [comment]
Podríamos crear una encuesta usando Google Form, y en el mensaje de bienvenida, darle el enlace para que el nuevo miembro la llene. ¿Que dicen? 

cc 
@Skatox @abr4xas @JMEspiz @jobsamuel

**Comment by abr4xas** [comment]
+1 me parece bien :D

----
ángel cruz
http://blog.abr4xas.org
GNU/Linux counter #50841
1CKAD1wr9cajXDp5Am3c11GU25peGTB67k

On Fri, Apr 28, 2017 at 8:52 AM, Andrés Villanueva <notifications@github.com

**Comment by jobsamuel** [comment]
Me parece chevere, pero que tal si en vez de utilizar Google Forms hacemos esto:

- Cada vez que un nuevo miembro entre, Wengy le pregunta: _cómo llegó al grupo_.
- Wengy registra los mensajes posteriores a esa respuesta o replies.
- Se guarda ese registro en alguna DB (e.j.: Firebase o una spreadsheet del Google Form).

La idea es hacer todo exageradamente fácil para obtener la mayor cantidad de data posible :sunglasses:

**Comment by Villanuevand** [comment]
@jobsamuel 

Pero esto no afectaría el timeline del grupo?.

**Comment by jobsamuel** [comment]
¿Cómo así @Villanuevand ? :thinking:

**Comment by Villanuevand** [comment]
@jobsamuel 

Si la persona hace reply, veriamos su respuesta,  y si son varias preguntas?  No sería una especie de spam... 
Ojo, estoy pensando ya en el hecho no comentado, de que se podría colocar más de 1 pregunta en la encuesta. Cosa que no estaba estipulada.

**Comment by jobsamuel** [comment]
La propuesta está pensada en una sola pregunta @Villanuevand , la cual no alteraría en lo absoluto el _timeline_ ya que sería lo mismo que poner un link para una encuesta. Para 2 o más preguntas no tengo la solución, aún :disappointed:

**Comment by Villanuevand** [comment]
@jobsamuel 

Tienes razón, entonces podemos decir que: 

Una vez que el nuevo miembro llega, se le envía 2 mensajes:
 - Mensaje de Bienvenida habitual.
 - Mensaje com la pregunta, haciendole `@mention` al nuevo miembro.  

Especificando en el segundo mensaje, debemos especificar que para contestar la encuenta solo debe hacer  `reply`. 

¿Ese sería el criterio? 

cc @leocabeza

**Comment by jobsamuel** [comment]
Sólo falta verificar (o confirmar), que el API de Telegram retorne la ID o alguna referencia del mensaje al cual se le hace reply. Si es es 100% posible, entonces estaremos estupendo :metal:

**Comment by leocabeza** [comment]
Si es posible @jobsamuel, lo qué pasa es que hacerlo así tomaría más tiempo (hay muchas cosas aquí, el usuario puede no responder, responder sin hacer mención a wengy, no contestar con el primer reply, conectar con firebase).

La idea del enlace de Google forms que propuso @Villanuevand me parece mucho más fácil de implementar.

Dicho lo anterior, creo que sería mejor que el usuario hiciera todo sin tener que salir de la aplicación.

**Comment by jobsamuel** [comment]
> Si es posible @jobsamuel, lo qué pasa es que hacerlo así tomaría más tiempo (hay muchas cosas aquí, el usuario puede no responder, responder sin hacer mención a wengy, no contestar con el primer reply, conectar con firebase).

Claro que **no será fácil** @leocabeza , pero será un reto divertido que podrá tener otros casos de uso. Sin embargo, conectar con Firebase es un viaje (fácil) en caso que se decida utilizarlo, y las respuestas sin mención u otras variaciones simplemente se descartan para la primera versión. Sólo se aceptan los replies ideales y listo.

Además, considero que es la única solución elegante que cumple con el requisito que nos gustó: _no salir de la aplicación_  :sparkles:

**Comment by dianjuar** [comment]
Opino, que la propuesta de Google Form es bastante buena.
Se puede implementar ya mismo sin ninguna dificultad. Se tiene un prototipo totalmente funcional en muy poco tiempo (menos de 1 hora). 
Se puede implementar mientras se desarrolla el reply al bot, así se puede obersvar la aceptación de los nuevos miembros, calidad de preguntas, etc...

**Comment by jobsamuel** [comment]
Chévere @dianjuar :raised_hands: Primero la opción fácil y luego la _"dificil"_ con el objeto de validar la aceptación. Te apoyo :100:

**Comment by Villanuevand** [comment]
Ok, me parece bastante salomónica lo que comenta @dianjuar 

Aquellos a favor de implementar un Google Form, como primer version...  

Votar con 👍  o con 👎    en este comentario... 
 
cc @leocabeza  @jobsamuel  @dianjuar @abr4xas

**Comment by leocabeza** [comment]
Ok, entonces... ¿Quien hace el Google Form con las preguntas?

**Comment by jobsamuel** [comment]
Debería hacerlo @Villanuevand por proponerlo :smile:

**Comment by Villanuevand** [comment]
@jobsamuel : 

¡Jajajaja! sin problemas...

**Comment by Villanuevand** [comment]
### Pregunta
¿Cómo te enteraste de ngVenezuela?

### Opciones

- Twitter
- Facebook
- Google 
- Medium
- OpenVE - Comunidades Telegram
- Un amigo

**Comment by dianjuar** [comment]
@Villanuevand No hace falta la opción [Comunidades Telegram](https://github.com/OpenVE/comunidades-en-telegram) ?

Yo entré por ahí.

**Comment by Villanuevand** [comment]
@dianjuar  ¡Listo! Modificado mensaje... 

¡Mil gracias!

**Comment by dianjuar** [comment]
Tocando el tema de los reply del bot, de qué pasa cuando sean muchas preguntas y si esto afectará el timeline del grupo, Tengo la solución...

**Que el usuario responda todo esto de manera privada al bot...**

### Cómo se hace?
Cuando entre Wegny le da la bienvenida, le dice lo que le tenga que decir como siempre se ha hecho. 
Luego en un segundo mensaje para que el usuario no se pierda entre tanta prosa se le dice que se está realizando una encuesta y se le da un enlace personalizado (no recuerdo el nombre técnico).

**Ejm:**

> Estamos realizando una encuesta a los nuevos miembros para dios sabrá qué....
> Si te apetece puedes realizarla acá [t.me/wegnybot?encuesta]()

Este enlace lo redirige a un conversación privada con wegny y ella sabrá que se trata de un nuevo miembro gracias a la variable del enlace y le soltará la encuesta, el usuario responderá sin necesidad de hacer reply, simplemente lanza la pregunta y espera una respuesta, como una conversación fluida.

-----------------------

De esta manera el usuario no se cohíbe de responder en publico, no afecta el timeline, se le da un trato personalizado al nuevo miembro.

Lo de la variable en el enlace es técnicamente posible, lo leí hace tiempo en la documentación oficial de telegram.

**Comment by abr4xas** [comment]
Hola amiwitos, vengo yo a preguntar algo que no se si ya lo escribieron pero como escribieron mucho me da algo de flojera leer...

No es más facil (_digo yo_) enviarle un PV a esa persona con todo lo que se le quiera preguntar?

**Comment by jobsamuel** [comment]
> pero como escribieron mucho me da algo de flojera leer...

@abr4xas debes leer :grimacing:

**Comment by Villanuevand** [comment]
Cerrado en #43
