### ISSUE TITLE
Escribir un mensaje al grupo, cuando se haga un release de una nueva versión de Angular

### ISSUE THREAD

**Issue by leocabeza** [ngVenezuela/wengy-ven#35]
**Estoy enviando un ...**  (marque con una "x")

```
[ ] Error reportado (Haz referencia al issue) => (Busca en github un issue o PR antés de enviar uno, NO olvides borrar esto).
[*] Solicitud de caracteristica, mejora. (Haz referencia al issue, marcado como "Mejora", NO olvides borrar esto)

```

**Comportamiento Actual** 
NO APLICA

**Comportamiento Esperado**
Escribir un mensaje, cuando salga una nueva versión de angular 1.x o 2.x

**Reproducción del Problema**
NO APLICA

**Cual es el motivo / Caso util para cambiar el comportamiento?**
NO APLICA

**Por favor cuentamos sobre tu ambiente de desarrollo:**
NO APLICA

**Comment by osnoser1** [comment]
Lo muuuy poco que he leído es que si utilizar superfeedr y este enlace: https://github.com/angular/angular/releases.atom
Aparentemente superfeedr usa webhooks?...

Pero no tengo idea de si es viable y si por ahí van los tiros.

¿Qué piensan?

**Comment by Villanuevand** [comment]
Esta buena esa opción @osnoser1 , lo que habría que hacer es que wengy parsee el xml, @leocabeza que opinas?

**Comment by leocabeza** [comment]
Se ve fácil y _doable_ en un tiempo razonable.

**Comment by Villanuevand** [comment]
@leocabeza  Deberiamos buscar algun servicio que nos avise sin necesidad de tener que estar mirando el feed y parseandolo.

**Comment by leocabeza** [comment]
Qué me corrija alguien si me equivoco, pero la única manera de hacer esto es mediante un webhook en github dentro del repo de angularjs, de lo contrario toca estar mirando el feed y parseandolo. @Villanuevand

**Comment by osnoser1** [comment]
Esa es mi idea principal, utilizar superfeedr  o algún servicio similar que utilice webhooks para dos cosas:

1. Obtener en tiempo real información cuando actualicen Angular.
2. No tener que estar consultando cada cierto tiempo el repositorio.

El enfoque que yo veo es, suscribirse a los cambios de contenido con superfeedr al enlace .atom que publiqué, y en teoría superfeedr en lo que detecte un cambio nos notifica a través del webhook configurado previamente con su api.

Cuando dices un webhook en github dentro del repo de angularjs, no sé si te refieres a la característica de github en donde en sus opciones puede especificar un enlace de una página para utilizar el webhook.

@Villanuevand, @leocabeza

**Comment by leocabeza** [comment]
Si, @osnoser1 , me refiero al webhook dentro del repo de angularjs, al cual nadie tiene acceso.
Creo que la solución con superfeedr, en este caso, es la mejor opción.

**Comment by osnoser1** [comment]
¿Tienen planes de implementar esta característica en el corto plazo?
De no ser así puedo trabajar en ella...

**Comment by leocabeza** [comment]
Pues yo personalmente, no. Entonces hágale y cualquier duda avisas. @osnoser1

**Comment by Villanuevand** [comment]
Listo @osnoser1 el issue está asignado a tí.
Cualquier duda o ayuda que necesites, puedes hacer `mention` en otro un comentario a cualquiera.

**Comment by leocabeza** [comment]
Sería bueno un update de esta funcionalidad @osnoser1 @Villanuevand. Yo tengo disponibilidad para trabajar en ella.

**Comment by osnoser1** [comment]
Hola @leocabeza, no he tenido disponibilidad en trabajar con esa característica, mas sin embargo con todo el movimiento de wengy me había puesto a trabajar en la integración, si puedes y quieres dame este fin de semana pasar trabajar en la característica, y hago un pull para que veas los cambios y cualquier cosa trabajamos juntos, te parece?

**Comment by leocabeza** [comment]
Si @osnoser1, me parece bien. Avisame cualquier cosa.
