### ISSUE TITLE
Crear un Gist automáticamente, cuando el usuario coloca código en el chat

### ISSUE THREAD

**Issue by leocabeza** [ngVenezuela/wengy-ven#36]
**Estoy enviando un ...**  (marque con una "x")

```
[ ] Error reportado
[*] Solicitud de caracteristica, mejora.

```

**Comportamiento Actual** 
NO APLICA

**Comportamiento Esperado**
Escuchar un mensaje que cumpla el formato de que es algún codigo o snippet, y subir ese código a gists, luego responder al usuario con ese enlace que se creó. No lo veo muy díficil de implementar:
https://developer.github.com/v3/gists/#create-a-gist

**Reproducción del Problema**
NO APLICA

**Cual es el motivo / Caso util para cambiar el comportamiento?**
Muchas veces los usuarios copian y pegan código en el chat, y por lo general los administradores les recomiendan que hagan un gist. Con esta funcionalidad, el gist se crearía automáticamente como respuesta al usuario.

**Por favor cuentamos sobre tu ambiente de desarrollo:**
NO APLICA

**Comment by Villanuevand** [comment]
Uy! este está muy interesante... 
Pero @leocabeza .. 
¿Cómo sabes que es codigo? ...

**Comment by leocabeza** [comment]
@Villanuevand quizás alguna expresión regular, hay muchas palabras de JS y AngularJS que son propias del lenguaje/framework.

**Comment by jobsamuel** [comment]
Tal vez se podría simiplicar todo con tan sólo verificar si un mensaje tiene: 

> *```*

Además, se verifica si el string dentro de esas "comillas" tiene una longitud considerable, con el objeto de evitar crear gists cuando alguien las use para enviar una URL, nombre expresión, etc.

**Comment by leocabeza** [comment]
Creo que si sólo vamos a tomar en cuenta el código que tenga 

> *```*

No es tan mala opción. Definimos una longitud fija, y que cree el gist con: https://developer.github.com/v3/gists/#create-a-gist

**Comment by davidjsalazarmoreno** [comment]
En serio que este issue está bastante interesante, he montado una prueba de concepto en [ngve-issue-36-gist](https://github.com/ngVenezuela/wengy-ven/tree/ngve-issue-36-gist), para crear un gist público y anonimo sería así /gist códigoAqui.

```
/gist function newText(msg) {
  if (!goodMorningGivenToday && isGoodMorningGiven(msg.text)) {
    goodMorningGivenToday = true;
  }

  function isGoodMorningGiven(text) {
    return goodMorningRegExp.test(text);
  }
}
```
Resultado:
https://gist.github.com/0c67353de991620c49afc7b44ae37243

No tengo idea cómo detectar los ``` 😂, es decir lo intenté con Regex (  /\`{1,3}(.|\n)*\`{1,3}/g ) pero el evento onText no se dispara (pero seguro es una novatada mía con respecto al API de telegram 😅).

**Comment by davidjsalazarmoreno** [comment]
¿Qué piensan? @leocabeza @jobsamuel @Villanuevand

**Comment by Villanuevand** [comment]
@davidjsalazarmoreno ¡Brutal que le estás metiendo el pecho a este issue! 

Por que no intentas con el ascii `/\u0060/` ? 

Te asignaré este issue, ¿te parece?

**Comment by davidjsalazarmoreno** [comment]
Fino @Villanuevand, asignalo, voy a intentar con el  ASCII a ver.

**Comment by dianjuar** [comment]
Hola @davidjsalazarmoreno, puedes usar [regex101.com](regex101.com) para probar tus expresiones regulares, incluso compartirlas dado el caso que quieras pedir ayuda o te quedes atorado. 

> Desde que lo descubrí voy allá primero a probar mis expresiones regulares antes de montarlas en mi proyecto.

**Comment by leocabeza** [comment]
Faltaría también tomar en cuenta la longitud del texto antes de mandar el gist @davidjsalazarmoreno

**Comment by Villanuevand** [comment]
¿Pregunta? @davidjsalazarmoreno  ❓
Se podrá colocar algún _Prefijo_ o _Sufijo_ en el nombre del gist? ... ❓

**Comment by davidjsalazarmoreno** [comment]
@dianjuar si de hecho ayer la había probado allí y parece funcionar bien, a pesar de eso el evento onText no se dispara, ¿quizás es que está enviando no es el markdown sino el html ya compilado (el tag pre)?, voy a chequear eso. 

[https://regex101.com/r/zHKllf/1](https://regex101.com/r/zHKllf/1)

@leocabeza ¿de cuánto le colocamos el limite?, ¿doscientos caracteres?.

@Villanuevand En la prueba de concepto el nombre del gist toma la fecha actual y por defecto a **.js** pero debería ser posible que el usuario indique algún prefijo/sufijo si lo desea.

En [inline_mode](https://core.telegram.org/bots/inline) de telegram se ve interesante, algo así como...

```
Elija su extensión
[ .js [ X ] ] [ .css ] [ .php ]
@gist console.log('Hola mundo');
```
...pero no sé si es complicarse mucho la vida.

**Comment by leocabeza** [comment]
Yo creo que sería mejor no darle la opción al usuario, no sé la razón por la cual @Villanuevand hizó la pregunta. @davidjsalazarmoreno.

Yo pienso que si podríamos empezar con 200 👍

**Comment by Villanuevand** [comment]
@leocabeza , 

Mi pregunta fué solo por curiosidad... 

cc  @davidjsalazarmoreno

**Comment by davidjsalazarmoreno** [comment]
Yaaa que tonto, no era la expresión que estaba fallando, el bot que estaba utilizando para pruebas tenía la privacidad activada por eso no se disparaba el evento para los mensajes del grupo de pruebas (mala mía XD).

Un gist se crea automáticamente cada vez que se envía un mensaje con ``` código ``` sólo si no supera los 200 caracteres de longitud.

En la descripción del gist se usan los datos del usuario quien lo creo (first name, last name y username).

[PR 52 (Por favor testear bastante)](https://github.com/ngVenezuela/wengy-ven/pull/52)

PS: He agregado node-fetch como dependencia, ¿no hay rollo?, me comentan cualquier cosa.

**Comment by Villanuevand** [comment]
Solventado en #52
