### ISSUE TITLE
Preguntar Ubicación para meetups

### ISSUE THREAD

**Issue by Royedc4** [ngVenezuela/wengy-ven#4]
Solicitar información sobre ubicación a cada miembro para unirnos localmente y hacer meetups

**Comment by davidjsalazarmoreno** [comment]
Esta también se ve interesante, ¿podrían por favor expandirla para entender la mejora?.

**Comment by leocabeza** [comment]
Este issue no ha tenido mucha actividad ni tracción en los últimos meses. ¿Que podríamos hacer con este issue? @ngVenezuela/admins

**Comment by JMEspiz** [comment]
@leocabeza yo creo que esta info se puede recoger con un link a google forms. El mismo que se llena para saber por que medio conocieron la comunidad.

**Comment by Villanuevand** [comment]
A mi criterio, descartarla. 

@JMEspiz No, la encuesta no se está preguntando ubicación. Solo preguntamos sobre el canal por el que llego a la comunidad. 

@leocabeza Sientete libre de cerrar el issue cuando quieras...

**Comment by JMEspiz** [comment]
@Villanuevand exacto, la encuesta no pregunta la ubicación. Pero si en alguna comunidad quieren usar wengy y tienen esta necesidad pueden facilmente usar la opción de google form.

**Comment by leocabeza** [comment]
Yo creo que está sería una característica totalmente distinta @JMEspiz.
Si hay algún interés, podemos abrir más adelante este issue... de momento lo pongo cerrado.
