### ISSUE TITLE
Mal renderizado al mensaje de bienvenida de wengy

### ISSUE THREAD

**Issue by dianjuar** [ngVenezuela/wengy-ven#49]
```
[x] Error reportado 

[ ] Solicitud de caracteristica, mejora. 

```

**Comportamiento Actual** 
Como se ve en la imagen, el mensaje que envía wengy a los nuevos usuarios tiene saltos de línea entre oraciones.
![image](https://cloud.githubusercontent.com/assets/7026066/25689296/cda8ac92-3054-11e7-81df-3c750fc22f10.png)

**Comportamiento Esperado**
Que el mensaje no tenga saltos de línea entre las oraciones..
Cuando yo entré no pasaba

![image](https://cloud.githubusercontent.com/assets/7026066/25689405/c1412460-3055-11e7-9f26-bca741e8a7e4.png)

**Reproducción del Problema**
Cada vez que entra un usuario nuevo al grupo.

**Cual es el motivo / Caso util para cambiar el comportamiento?**
Al ser lo primero que ve el nuevo integrante, me parece que puede dar la sensación que no se le da atención a los detalles o todo lo que realizamos se hace a medias y sin ganas... **Es la primera impresión que se lleva la persona de la comunidad.**

**Por favor cuentamos sobre tu ambiente de desarrollo:**
No aplica

----------------

# ¿Cómo resolverlo?

El error se introdujo en el pullrequest #45 especificamente en el archivo [`messages.js`, línea 2, columna 14](https://github.com/ngVenezuela/wengy-ven/pull/45/commits/2ca8c3d535c5c3a75481c28eb8b991d9adcee4ab?diff=unified#diff-c89b136ac1e13ad05fc7740b726854d6R2) que se cambió una comilla `'` por el backstick <code>&#96;</code> en el string que contiene el mensaje.

**Comment by Villanuevand** [comment]
@dianjuar  ¡Buen día! 
Me tomé el abuso de asignarte esta incidencia, por el alto grado de conocimiento sobre la misma.  

Es importante que nos notifiques cuando comenzarás a desarrollar, para mover la tarjeta en el project... Cualquier otra duda adicional que tengas sobre cómo es el proceso de colaboración avisame... 

¡Quedo atento a tus comentarios!

**Comment by dianjuar** [comment]
@Villanuevand I'm working on it.

**Comment by Villanuevand** [comment]
Cerrado en PR #54
