### ISSUE TITLE
Mejora en Template para issues. 🔖

### ISSUE THREAD

**Issue by Villanuevand** [ngVenezuela/wengy-ven#50]
**Estoy enviando un ...**  (marque con una "x")

- [ ] Error reportado (Haz referencia al issue) 

- [x] Solicitud de caracteristica, mejora. 

**Comportamiento Actual** 
Tanto el _TEMPLATE_ISSUES_ como el _TEMPLATE_PULL_REQUESTS_ poseen la misma estructura. Lo cual puede ser confuso y no se ajusta a las caracteristica de cada evento.

**Comportamiento Esperado**
TEMPLATES distintos, según el evento, bien sea _ISSUES_ o _PULL_REQUESTS_

**Reproducción del Problema**
_No Aplica_

**Cual es el motivo / Caso util para cambiar el comportamiento?**
Ser congruentes con lo que significa cada evento, y evitar confusiones entre los colaboradores. 

**Por favor cuentamos sobre tu ambiente de desarrollo:**
_No Aplica_

**Comment by dianjuar** [comment]
Apoyo totalmente esto... Las plantillas actuales son muy extensas, burocráticas y a veces no vienen al caso...

Parecen sacadas de un libro de una metodología formal

**Comment by Villanuevand** [comment]
Todos los que quieran participar en esto, estaría genial. Como venimos haciendo en otros issues,  los comentarios son todo nuestros! 😎

**Comment by dianjuar** [comment]
y si nos basamos en algún proyecto muy activo a nivel de contribuciones?

El mismo [Angular](https://github.com/angular/angular), [Ruby on Rails](https://github.com/rails/rails), [Nativescript {N}](https://github.com/NativeScript/NativeScript) ...

**Comment by Villanuevand** [comment]
El método de commits, recomendado en el contributing.md esta basado en Angular. 
POdríamos  buscar una guía de estilos, quizas la de [airbnb](https://github.com/airbnb/javascript)?

**Comment by osnoser1** [comment]
El método de commits me parece excelente.
Abre la posibilidad de automatizar la generación del changelog y el número de versión.

Con respecto a la plantilla de los PR, aquí esta la del equipo de [Angular](https://github.com/angular/angular/blob/master/.github/PULL_REQUEST_TEMPLATE.md) y este es un [ejemplo](https://github.com/angular/angular/pull/16751) de como la usan.

Se podría adaptar a nuestras necesidades, quizás.

**Comment by leocabeza** [comment]
Entonces estamos de acuerdo que debemos cambiar es el Template de PR?

Si es así, me gusta mucho el template que tiene el equipo de angular que comentó @osnoser1

**Comment by Villanuevand** [comment]
@leocabeza  Si definitivamente debemos... 
Y revisar si el de `PR` puede evolucionar para mejorar ...

**Comment by leocabeza** [comment]
Bueno, ya yo di mi opinión @Villanuevand, ¿Qué necesitamos lograr para dar esta tarea como terminada?

**Comment by Villanuevand** [comment]
@leocabeza Definir cómo sería el nuevo template y armarlo... 
¡basicamente eso!

**Comment by leocabeza** [comment]
Cerrado en #120
