### ISSUE TITLE
Conocer cuando un usuario se va de la comunidad, para saludarlo 🙂

### ISSUE THREAD

**Issue by Villanuevand** [ngVenezuela/wengy-ven#51]
**Estoy enviando un ...**  (marque con una "x")

-  Error reportado (Haz referencia al issue) 

- ✅ Solicitud de caracteristica, mejora. 

**Comportamiento Actual** 
No hay mensaje de notificación cuando un usuario se va del grupo.

**Comportamiento Esperado**
Recibir un mensaje notificando cuando un usuario se ha ido.

**Reproducción del Problema**
_No Aplica_

**Cual es el motivo / Caso util para cambiar el comportamiento?**
Solo por chismear, quien se va del grupo. 

**Por favor cuentamos sobre tu ambiente de desarrollo:**
_No Aplica_

**Comment by JuanDelgadillo** [comment]
Solo por chismear 😂

**Comment by Villanuevand** [comment]
@JuanDelgadillo ¡Tu conoces mi sinceridad! ...

@leocabeza  ... ¡Estaba investigando para hacerlo yo!  😪

**Comment by leocabeza** [comment]
Bueno, si lo vas a hacer, asignatelo @Villanuevand!

**Comment by leocabeza** [comment]
Cerrado en https://github.com/ngVenezuela/wengy-ven/pull/61
