### ISSUE TITLE
Definir una guía de estilo o convención

### ISSUE THREAD

**Issue by leocabeza** [ngVenezuela/wengy-ven#53]
**Estoy enviando un ...**  (marque con una "x")
```
[ ] Error reportado (Haz referencia al issue) => (Busca en github un issue o PR antés de enviar uno, NO olvides borrar esto).
[*] Solicitud de caracteristica, mejora. (Haz referencia al issue, marcado como "Mejora", NO olvides borrar esto)

```

**Comportamiento Actual** 
Se usa ESLint con config de airbnb y algunas reglas personalizadas.

**Comportamiento Esperado**
Definir entre todos una guía de estilo adecuada para trabajar con ella.

**Reproducción del Problema**
No aplica

**Cual es el motivo / Caso util para cambiar el comportamiento?**
Inconsistencia entre código entre devs

**Por favor cuentamos sobre tu ambiente de desarrollo:**
No aplica

**Comment by Villanuevand** [comment]
¿Cuales son los puntos a tener en cuenta para poder dar como **Hecho** esta incidencia?

**Comment by davidjsalazarmoreno** [comment]
¿https://standardjs.com?, aunque si ya están usando la de airbnb pues seguir con esa.

**Comment by leocabeza** [comment]
Supongo que ponerse de acuerdo con alguna, @Villanuevand. Pues la de airbnb no me parece tan mal, si tienen alguna otra sugerencia, es bienvenida.

**Comment by leocabeza** [comment]
Se implementó la guía de estilos de `airbnb`, y se modificó el archivo `.eslintrc.json` para incluirla en #66 .
