### ISSUE TITLE
Uso de SemVer

### ISSUE THREAD

**Issue by osnoser1** [ngVenezuela/wengy-ven#57]
**Estoy enviando un ...**  (marque con una "x")
```
[x] Error reportado.
[ ] Solicitud de característica, mejora. (Haz referencia al issue, marcado como "Mejora", NO olvides borrar esto)

```

**Comportamiento Actual** 
La última versión publicada es la 1.0.2.

**Comportamiento Esperado**
Debido a que se añaden características y solución de errores compatibles hacia atrás la nueva versión debió ser 1.1.0.

**Reproducción del Problema**
_No aplica_ 

**Cual es el motivo / Caso util para cambiar el comportamiento?**
_No aplica_

**Por favor cuentamos sobre tu ambiente de desarrollo:**
_No aplica_

**Comment by Villanuevand** [comment]
@osnoser1  Precisamente estabamos hablando de ello...

**Comment by Villanuevand** [comment]
Acá los cambios introducidos en el último despliegue a producción: 

- Se publica una entrada en el grupo cuando se publica una entrada en https://medium.com/ngvenezuela #39. (mejora)
- Se le envía una encuesta a los nuevos miembros de la comunidad #3. (mejora)
- Se implementó Jest para Unit testing #11. (mejora)
- Se corrigió el renderizado del mensaje de bienvenida #49. (Error)
- Se crea automáticamente un gist cuando el usuario coloca un código en el chat #36 (Mejora) 

### SEMVER nos dice:  

#### La versión patch Z (x.y.Z | x > 0) 
>DEBE incrementarse cuando se introducen solo arreglos compatibles con la versión anterior. 
>Un arreglo de bug se define como un cambio interno que corrige un comportamiento erróneo.

#### La versión minor Y (x.Y.z | x > 0) 
>DEBE ser incrementada si se introduce nueva funcionalidad compatible con la versión anterior. 
>Se DEBE incrementar si cualquier funcionalidad de la API es marcada como deprecada.
>PUEDE ser incrementada si se agrega funcionalidad o arreglos considerables al código privado. >Puede incluir cambios de nivel patch. La versión patch DEBE ser reseteada a 0 cuando la versión > >minor es incrementada.

##### La versión major X (X.y.z | X > 0) 
>DEBE ser incrementada si cualquier cambio no compatible con la versión anterior es introducida a >la API pública.PUEDE incluir cambios de niver minor y/o patch. Las versiones patch y minor DEBEN >ser reseteadas a 0 cuando se incrementa la versión major.

### Entonces recapitulando..

- Se publica una entrada en el grupo cuando se publica una entrada en https://medium.com/ngvenezuela #39. (mejora) => *minor (1)*
- Se le envía una encuesta a los nuevos miembros de la comunidad #3. (mejora) =>*minor (2)*
- Se implementó Jest para Unit testing #11. (mejora) => *patch (1)*
- Se corrigió el renderizado del mensaje de bienvenida #49. (Error) => *patch (2)*
- Se crea automáticamente un gist cuando el usuario coloca un código en el chat #36 (Mejora)  => *minor (3)*

## La versión correspondiente a este release sería: 
`1.3.2` 

¿Es mi apreciación correcta?

**Comment by osnoser1** [comment]
Lo que pienso es lo siguiente: 

Si se hace un deploy por cada commit que se hizo el incremento de versión se haría de la forma que comentas.

Pero si de la última versión que fue 1.0.1 se hizo un despliegue después de todos los commits que se comentan entonces debería cambiar a 1.1.0.

Fíjate que en `La versión minor Y (x.Y.z | x > 0)` dice:

> La versión patch DEBE ser reseteada a 0 cuando la versión minor es incrementada.

Ahora, dice también:
> Puede incluir cambios de nivel patch.

Lo que significa que puede contener solución a errores, mas sin embargo, no por eso se incrementa el número a nivel de patch.

**En resumen:**

Si al momento de hacer el despliegue, se han añadido n cantidad de nuevas características compatibles hacia atrás, se incrementa en 1 la versión menor y se resetea el número a nivel de patch.

Independientemente de dicha versión tenga solución de errores, el comportamiento del cambio de versión menor se mantiene, es decir, se resetea el número a nivel de patch.

¿Sí me explico?

**Comment by leocabeza** [comment]
Me queda más claro como lo comenta @osnoser1. La pregunta sería: ¿Se puede cambiar el tag de una vez o se hace desde el siguiente release?

**Comment by osnoser1** [comment]
Pienso que sería mejor desde el siguiente release.

**Comment by Villanuevand** [comment]
Estoy mirando los releases de proyectos conocidos y en la mayoría, se nota organización en los tags, ya que los que aumentan de patch, solo hacen "bug fixing", y los que aumenta de minor, se abocan exclusivamente desarrollar nuevas funcionalidades retocompatibles. 

Así que lo que dice @osnoser1  tiene bastante sentido. 
La versión actual debería ser la `1.1.0`.

Para próximas iteraciones deberiamos organizarnos mejor, pero me agrada mucho que se haya generado este debate porque nos da la oportunidad definir como actuaremos. 

Por otro lado pienso que debemos cambiarlo ahora mismo => https://help.github.com/articles/editing-and-deleting-releases/

**Comment by osnoser1** [comment]
Con respecto a cambiar el tag ahorita o en el siguiente release, imagina que ya se generó la versión y esa le llegó a cientos de personas, si se cambia aquí en github generaría un conflicto con respecto a las versiones desplegadas y lo que está aquí.

Quizá, otra alternativa sería generar una nueva versión ahorita mismo, desplegar para corregir el versionado. Estilo Angular, algo así.

**Comment by leocabeza** [comment]
También de acuerdo con @Villanuevand que se haga el cambio de una. Y se tome en cuenta para los siguientes releases el uso de SemVer.

**Comment by leocabeza** [comment]
También me gusta esa idea @osnoser1 . ¿Quizás generar una v1.1.1?

**Comment by Villanuevand** [comment]
Me gusta la idea de generar una version `1.1.1`

**Comment by osnoser1** [comment]
Me parece bien.

Hay otras cosas que pienso que se deberían hacer en el despliegue y versionado, pero ya será motivo de conversación en otro issue. 😄

**Comment by cesarfrick** [comment]
Creo que la idea de @osnoser1 es la más conveniente para este caso, tiene mucho sentido

**Comment by leocabeza** [comment]
Este cambio ya quedó en: https://github.com/ngVenezuela/wengy-ven/releases/tag/v1.1.1

**Comment by ajsb85** [comment]
+1 (v1.1.0)
