### ISSUE TITLE
Notificar en el grupo cuando wengy tenga un nuevo release.

### ISSUE THREAD

**Issue by dianjuar** [ngVenezuela/wengy-ven#58]
**Estoy enviando un ...**  (marque con una "x")
```
[ ] Error reportado (Haz referencia al issue) 
[X] Solicitud de caracteristica, mejora.
```

**Comportamiento Actual** 

 _No aplica_ 

**Comportamiento Esperado**

 _No aplica_ 

**Cual es el motivo / Caso util para cambiar el comportamiento?**

Al implementarlo se logra
- Que todos los miembros de la comunidad se enteren de las nuevas mejoras de wengy 
- Dar impresión de ser una comunidad activa.
- Motivar a otros miembros a contribuir al desarrollo de wengy

**Por favor cuentamos sobre tu ambiente de desarrollo:**

 _No aplica_

**Comment by leocabeza** [comment]
Creo que la implementación sería muy similar a la de #35

**Comment by dianjuar** [comment]
@leocabeza es verdad... Abrí un duplicado

**Comment by leocabeza** [comment]
Esto no era un duplicado, aquí haces referencia a wengy, allá se hace referencia a Angular @dianjuar

**Comment by osnoser1** [comment]
Muchachos, si no tienen inconvenientes me gustaría asignarme esta tarea, ya la tengo casi lista, ustedes me dirán si les parece.

![photo_2017-05-22_08-17-21](https://cloud.githubusercontent.com/assets/1179744/26308631/048b286c-3ec8-11e7-876b-29f0a5da1c89.jpg)

**Comment by Villanuevand** [comment]
Si ya la tienes casí lista es toda tuya @osnoser1 ... 
Ahi te la asigno... 

¡Esta quedando brutal!
