### ISSUE TITLE
Actualización de enlace a SEMVER - README.md

### ISSUE THREAD

**Issue by Villanuevand** [ngVenezuela/wengy-ven#59]
**Estoy enviando un ...**  (marque con una "x")
```
[ ] Error reportado (Haz referencia al issue)
[x] Solicitud de caracteristica, mejora. 
```

**Comportamiento Actual** 
En el `readme.md` hay un enlace a el sitio oficial de SEMVER, pero en ingles.

**Comportamiento Esperado**
Que el enlace a SEMVER, que se encuentra en el `readme.md` apunte al site en español.

**Reproducción del Problema**
_No aplica_

**Cual es el motivo / Caso util para cambiar el comportamiento?**
Facilitar la lectura y el entiendimiento de SEMVER a los miembros de la comunidad. 

**Por favor cuentamos sobre tu ambiente de desarrollo:**
_No Aplica_

**Comment by leocabeza** [comment]
De momento, la versión en español está en v2.0.0-rc.2, no sé si sea lo más ideal, o se deja el enlace y esperemos por la actualización a v2.0.0. Enlace: http://semver.org/lang/es/

**Comment by Villanuevand** [comment]
Podría colocarse para que los que estén investigando como colaborar en este proyecto. 

Y estár atento a el release estable...

**Comment by leocabeza** [comment]
Si, de acuerdo.
