### ISSUE TITLE
Uso de .editorconfig.

### ISSUE THREAD

**Issue by osnoser1** [ngVenezuela/wengy-ven#70]
**Estoy enviando un ...**  (marque con una "x")
```
[ ] Error reportado (Haz referencia al issue) => (Busca en github un issue o PR antes de enviar uno, NO olvides borrar esto).
[*] Solicitud de característica, mejora. (Haz referencia al issue, marcado como "Mejora", NO olvides borrar esto)

```

**Comportamiento Actual** 
Al utilizar el editor a la hora de hacer tabulaciones, los saltos de lineas al final del archivo, la codificación, entre otras cosas, toma en cuenta la configuración predeterminada del usuario, lo que produce que a la hora de formatear no siga las convenciones de estilos especificadas.

**Comportamiento Esperado**
Al existir un archivo .editorconfig, el formateo de un archivo sería el esperado.

**Reproducción del Problema**
Configurar cualquier editor para que la cantidad de espacios por tabulación sea 4.

**Cual es el motivo / Caso util para cambiar el comportamiento?**
Mayor tranquilidad para el desarrollador. 😃, y uniformidad a la hora de editar código.

**Por favor cuentamos sobre tu ambiente de desarrollo:**
Windows 10.
Visual Studio Code.

**Comment by osnoser1** [comment]
Propuesta de .editorconfig.

```
# Editor configuration, see http://editorconfig.org
root = true

[*]
charset = utf-8
indent_style = space
indent_size = 2
insert_final_newline = true
trim_trailing_whitespace = true

[*.md]
max_line_length = off
trim_trailing_whitespace = false

```

**Comment by Villanuevand** [comment]
@osnoser1 ¡Listo! 

Haz el `pull request` y vamos a cerrar este issue, si hay sugerencias de mejora, pues que hagan `pr` y listo! 

¿Sin problemas verdad?

¡'Gracias por la iniciativa!

**Comment by osnoser1** [comment]
Excelente... :D

**Comment by osnoser1** [comment]
Solucionado por #71
