### ISSUE TITLE
Modularizar los comportamientos del bot, para que otras comunidades puedan utilizarlo

### ISSUE THREAD

**Issue by leocabeza** [ngVenezuela/wengy-ven#74]
**Estoy enviando un ...**  (marque con una "x")
```
[] Error reportado
[*] Solicitud de característica, mejora.

```

**Comportamiento Actual** 
No existe

**Comportamiento Esperado**
Se espera que el _comportamiento_ de este bot, se pueda encapsular en módulos y/o clases, de tal manera que se puedan implementar sólo los _features_ necesarios para cada bot y personalizarlo para cada comunidad.

Ejemplo:

Wengy puede (A la fecha del 17 Abril del 2017):

- Dar los buenos días (en ciertas condiciones).
- Publicar un mensaje una vez al día (en caso de que hayan nuevas entradas en el blog que se configuró en _config.js_.
- Responder mensajes en los que se les menciona o se les responde directamente.
- Saludar a los nuevos miembros del grupo, despedir a los que salen del grupo.
- Crea un gist automáticamente cuando el usuario coloca un bloque de código (bajo ciertas condiciones).

Se requiere que cada una de estas características puedan ser activadas/desactivadas según la funcionalidad que se quiere con el bot, esto puede implicar mover gran parte del código a otro repo y que los bots que quieran utilizar ciertas características del _core_ lo puedan hacer (incluso wengy).

**Reproducción del Problema**
No aplica

**Cual es el motivo / Caso util para cambiar el comportamiento?**
Un _esqueleto_ de comportamientos para futuros bots de otras comunidades y que puedan personalizarlo.

**Por favor cuentamos sobre tu ambiente de desarrollo:**
No aplica

**Comment by leocabeza** [comment]
¿Se entiende @Villanuevand @edwinvrgs?

**Comment by osnoser1** [comment]
@leocabeza, y si en vez de separar el código en distintos repositorios, más bien se utiliza un enfoque estilo [Angular](https://github.com/angular/angular/tree/master/packages)?

Me explico:

En su repo tienen esta estructura:

```
packages/
    animations/
    common/
    compiler-cli/
    core/
    ...
```

Cada carpeta de esas es un módulo totalmente independiente, cada uno con su respectivo `package.json,` y pudiéndose descargar de `npm`, y los paquetes se llaman `@angular/core`, `@angular/common`, etc.

Me encanta la idea de este issue. 😃

**Comment by osnoser1** [comment]
Aunque leí otro repo, y por mi mente pasó un repo por cada feature...
Pero por lo que entiendo, un repo para todos los módulos, y otro donde sea Wengy como tal y los use.
¿Es así como lo comentas? 🙄

**Comment by leocabeza** [comment]
Pues igual no hay nada definido. Y si, así como comentas es como se me ocurre @osnoser1 , aunque pensandolo bien no sé si sea la mejor manera, porque cada módulo estaría con sus propias dependencias...

Ejemplo: Nosotros utilizamos `node-fetch` para hacer peticiones _http_. Entonces... ¿Qué pasa si alguien quiere utilizar `axios` u otra libreria para hacer peticiones _http_ a sus proyetos?

Otro caso es que pasa si alguien en vez de `api.ai` quieren utilizar el AI de Facebook, o el de Microsoft...

Entonces no sé que tan mantenible sea, a la larga, crear una interfaz para esas funcionalidades.

Quizás en el proyecto de Angular sea un poco distinto, porqué ya tienen todas las dependencias predefinidas.

**Comment by leocabeza** [comment]
Es importante que se deben comentar todas las funciones con [jsdoc](http://usejsdoc.org/) junto con este issue, y también a mi parecer, agregar pruebas unitarias a todo

**Comment by leocabeza** [comment]
Quizás esto sería una buena opción:

https://github.com/lerna/lerna

**Comment by leocabeza** [comment]
Tenemos que hacer un roadmap y hacer los cambios poco a poco

**Comment by dianjuar** [comment]
Si empezamos a hablar de patrones de diseño ?

**Comment by Villanuevand** [comment]
@dianjuar Tell me more!

**Comment by dianjuar** [comment]
Qué les parece si en vez de implementar una arquitectura desde 0 utilizamos una ya estructurada, conocida y documentada? 

https://nestjs.com/
Muchos de nosotros sabremos cómo movernos en _nestjs_ ya que está inspirado fuertemente en la arquitectura que tiene Angular.

El [module pattern](https://docs.nestjs.com/modules) ya está implementado al mejor estilo de Angular. Cada una de las funciones que tiene Wengy pudiese estar en un repo aparte en forma de módulos, las personas pueden hacer módulos más adelante para Wengy y poder ser instalados con `npm install wengy-twitter` por ejemplo.

A partir de ahí podemos implementar nuestras propias abstracciones, patrones, diseños, etc.

**Comment by leocabeza** [comment]
Yo creo que es mucha complejidad añadida @dianjuar, ¿Y si dejamos todo configurable para que el que quiera utilizar wengy-ven solo le haga fork y ya?
