### ISSUE TITLE
Mejorar el README.md para con las contribuciones

### ISSUE THREAD

**Issue by leocabeza** [ngVenezuela/wengy-ven#84]
**Estoy enviando un ...**  (marque con una "x")
```
[] Error reportado
[*] Solicitud de caracteristica, mejora

```

**Comportamiento Actual** 
No está claro como contribuir de una manera más clara, desde el momento que obtenemos el token del bot, hasta como configurar los tokens de twitter, o como obtener el `groupId` para hacer pruebas en nuestro entorno de desarrollo. 
Así mismo, hay un `typo` aquí: https://github.com/ngVenezuela/wengy-ven#installación

**Comportamiento Esperado**
Resumir de manera detallada como configurar el proyecto para comenzar a contribuir más fácilmente.

**Reproducción del Problema**
No aplica

**Cual es el motivo / Caso util para cambiar el comportamiento?**
Mejorar la documentación respecto a como configurar el proyecto para que más personas puedan colaborar.

**Por favor cuentamos sobre tu ambiente de desarrollo:**
No aplica

**Comment by dianjuar** [comment]
### Excelente!
Opino que lo mejor es hacer una página en la wiki del repo y en el ReadMe.md hacemos referencia a la página.

**Comment by leocabeza** [comment]
De acuerdo @dianjuar

**Comment by leocabeza** [comment]
Ya comencé a hacer las modificaciones, pueden echarle un ojo y me comentan cualquier cosa, entre hoy y mañana la termino:

https://github.com/ngVenezuela/wengy-ven/wiki/Instrucciones-para-colaborar-con-el-proyecto

**Comment by leocabeza** [comment]
Cerrado en #92, cualquier cosa se abre otro issue para editar lo que está en el wiki

**Comment by dianjuar** [comment]
Excelente! 

Lo que ni me quedó claro es para que sirve el ngrok

**Comment by leocabeza** [comment]
@dianjuar hace unos días se hizó una modificación para que los *updates* de Telegram nos llegaran directamente a nuestro mini-servicio en express, para que Telegram pueda _vernos_ necesitamos tener un dominio/IP pública, y *ngrok* nos permite exponer nuestra maquina de desarrollo a Internet, a través de un tunel. ¿Me explique bien?

**Comment by dianjuar** [comment]
@leocabeza ok ok... Leyendo sobre entornos de trabajo me topé curiosamente con ngrok y lo entendí.

> [ngrok](https://ngrok.com/) is a small service and command line tool I use to share my local work over the internet. ngrok creates secure tunnels to a local environment, exposing your application on a special URL like http://7bbc49aa.ngrok.io.
